import type { Metadata } from "next";

import "./globals.css";
import { CartContextProvider } from "./context/cartcontext";
import Layout from "@/components/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartContextProvider>
          <Layout>{children}</Layout>
        </CartContextProvider>
      </body>
    </html>
  );
}
